import 'package:flutter/material.dart';
import 'package:i_can_fly/dao/flight-dao.dart';
import 'package:i_can_fly/dao/flight_dao.dart';
import 'package:i_can_fly/entity/flight.dart';

/// A StatefulWidget that provides a form to add a flight reservation.
///
/// This widget interacts with a FlightDao to save the flight details into a database.
class AddReservationPage extends StatefulWidget {
  /// The FlightDao instance for performing database operations.
  final FlightDao flightDao;

  /// Creates an instance of AddReservationPage.
  ///
  /// The [flightDao] parameter is required.
  const AddReservationPage({super.key, required this.flightDao});

  @override
  _AddReservationPageState createState() => _AddReservationPageState();
}

class _AddReservationPageState extends State<AddReservationPage> {
  final TextEditingController _departureCityController = TextEditingController();
  final TextEditingController _arrivalCityController = TextEditingController();
  final TextEditingController _airplaneTypeController = TextEditingController();
  DateTime? _departureDateTime;
  DateTime? _arrivalDateTime;

  /// Adds a flight to the database using the provided flight details.
  ///
  /// This method validates the input fields and creates a Flight object
  /// which is then saved to the database via the FlightDao. After the flight
  /// is successfully added, the current screen is popped from the navigation stack.
  void _addFlight() async {
    if (_departureCityController.text.isEmpty || _arrivalCityController.text.isEmpty) {
      // Optionally handle validation error, such as showing a Snackbar
      return;
    }

    final flight = Flight(
      id: null, // ID will be auto-generated by the database
      airplaneType: _airplaneTypeController.text,
      departureCity: _departureCityController.text,
      arrivalCity: _arrivalCityController.text,
      departureDateTime: _departureDateTime ?? DateTime.now(), // Consider using a DatePicker
      arrivalDateTime: _arrivalDateTime ?? DateTime.now().add(const Duration(hours: 2)), // Consider using a DatePicker
    );

    await widget.flightDao.createFlight(flight);
    Navigator.pop(context);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Add Flight Reservation"),
      ),
      body: SingleChildScrollView(
        child: Column(
          children: <Widget>[
            TextField(
              controller: _departureCityController,
              decoration: const InputDecoration(labelText: 'Departure City'),
            ),
            TextField(
              controller: _arrivalCityController,
              decoration: const InputDecoration(labelText: 'Arrival City'),
            ),
            TextField(
              controller: _airplaneTypeController,
              decoration: const InputDecoration(labelText: 'Airplane Type'),
            ),
            // Example buttons for picking dates would go here
            ElevatedButton(
              onPressed: _addFlight,
              child: const Text('Add Flight'),
            ),
          ],
        ),
      ),
    );
  }
}